Add creating integrity hash in checking update
team-apm/apm-data pull request #230
Opened 2022-06-10 15:15 UTC by hal-shu-sato

## Description

- Add creating integrity hash in checking update of packages on GitHub.
  - Find an archive file matched with a pattern.
  - Download the file.
  - Unzip the file.
  - Find the target file.
  - Create hash.
  - Write hash to a data file.

## Related Issue

## How Has This Been Tested?

It works fine on CLI.

## Checklist:

- [ ] ~~Updated the modification date in `mod.xml`.~~

2022-06-10 23:20 UTC, mitosagi commented on util/archive-name-pattern.json
> +  "#hebiiro/SelectAliasFolder": "SelectAliasFolder[0-9\\.]+",
`#`

2022-06-10 23:41 UTC, mitosagi requested changes
The code is working perfectly.

I would like to check something about the design of the json file. Sorry if I am missing the point.

2022-06-10 23:41 UTC, mitosagi commented on util/archive-name-pattern.json
> +  "#hebiiro/SelectAliasFolder": "SelectAliasFolder[0-9\\.]+",
`#`

2022-06-10 23:41 UTC, mitosagi commented on util/check-update.js
> +    if (Object.keys(archiveNamePattern).includes(id)) {
I would like to reduce the need to maintain `archive-name-pattern.json`. Can you set the condition to all packages for which releases exists, and use json only for repositories that have more than one downloadable zip file?

2022-06-10 23:41 UTC, mitosagi commented on util/check-update.js
> +        const targetPath = resolve(
Some files do not change their hashes with each release. How about updating the hash for all targets specified in previous releases?

2022-06-10 23:44 UTC, hal-shu-sato commented on util/archive-name-pattern.json
> +  "#hebiiro/SelectAliasFolder": "SelectAliasFolder[0-9\\.]+",
Now, I only support zip archives.
The files with # are 7z files.
I’ll support them in another PR.

2022-06-11 02:54 UTC, hal-shu-sato commented
I changed them.

2022-06-11 05:26 UTC, mitosagi requested changes
I think the logic is good.

2022-06-11 05:26 UTC, mitosagi commented on util/check-update.js
> +      if (extname(archiveData.name) === '.zip') {
It would be more convenient to filter at L168.
``` javascript
const assets = res.data.assets.filter((asset) => ... );
```

2022-06-11 05:26 UTC, mitosagi commented on util/check-update.js
> +            ? assets.find((value) => {
It would be helpful if {id} and {archiveNamePattern[id]} were displayed as errors when an asset is not found.

2022-06-11 05:26 UTC, mitosagi commented on util/check-update.js
> +            if (!existsSync(targetPath)) continue;
I think it should be interrupted with a "The files to be installed seem to have changed" error.

2022-06-11 07:11 UTC, hal-shu-sato commented
I fixed them.

2022-06-11 10:54 UTC, mitosagi approved these changes
Thanks for the changes.
It looks good to me.

2022-06-11 10:56 UTC, merged