ContentsTree・エフェクト並び替え・coord・丸付き折れ線テキストの4パッケージを追加
team-apm/apm-data pull request #325
Opened 2022-08-21 14:06 UTC by glyzinieh

## Description

- [ContentsTree](https://www.nicovideo.jp/watch/sm40465457)・[エフェクト並び替え](https://www.nicovideo.jp/watch/sm40952636)・[coord](https://www.nicovideo.jp/watch/sm32870150)・[丸付き折れ線テキスト](https://www.nicovideo.jp/watch/sm22558183)の4パッケージを追加
- 日付を更新

## Checklist:

- [x] Updated the modification date in `mod.xml`.

2022-08-21 14:12 UTC, hal-shu-sato reviewed
すみません……
一応IDのアルファベット順でソートしてます……
お伝えし忘れていました。申し訳ございません。
ご対応お願いします。

2022-08-21 14:23 UTC, glyzinieh commented
修正しました。
確認お願いします。

2022-08-21 14:36 UTC, hal-shu-sato commented
もしかして、`yarn fix`をかけ忘れていませんか？
念のため申し上げますと、体裁を整えるだけの場合は日時の更新は必要ありません。
よろしくお願いします。

2022-08-21 14:55 UTC, glyzinieh commented
経験が浅いもので理解できていませんでした。すみません
修正してプルリク出させていただきます。

2022-08-21 14:57 UTC, hal-shu-sato commented
いえいえー
わざわざPRありがとうございます。
ほんとは、`git commit`すれば自動で実行されるんですが、VS Codeなどだと実行されないので、そのあたりかなーと

2022-08-21 15:08 UTC, glyzinieh commented
VS Codeを使ってるので恐らくそれですね……
普段、触らない分野なのでよく分かってませんでした😓
確認よろしくお願いします。

2022-08-21 15:31 UTC, hal-shu-sato requested changes
数か所修正していただきたい点があります。
ご確認お願いします。

2022-08-21 15:31 UTC, hal-shu-sato commented on v3/packages.json
> +      "downloadURLs": ["https://www.nicovideo.jp/watch/sm40465457"],
```suggestion
      "downloadURLs": ["https://aviutl.techblog.jp/archives/aviutl_plugin_contentstree.html"],
```

2022-08-21 15:31 UTC, hal-shu-sato commented on v3/packages.json
> +      "downloadURLs": ["https://github.com/nazonoSAUNA/SortEffect/releases"],
```suggestion
      "downloadURLs": ["https://github.com/nazonoSAUNA/SortEffect/releases/latest"],
```

2022-08-21 15:31 UTC, hal-shu-sato commented on v3/packages.json
> +      "files": [{ "filename": "script/丸付折線テキスト.obj" }]
archivePathで"pointlinetext_obj_001/"が必要だと思います。

2022-08-21 15:31 UTC, hal-shu-sato commented on v3/packages.json
> +      "files": [{ "filename": "script/coord.anm" }]
archivePathで"coord/"が必要だと思います。

2022-08-21 15:31 UTC, hal-shu-sato commented on v3/packages.json
> +      "files": [{ "filename": "ContentsTree.auf" }]
archivePathで"ContentsTree_ver0.2/"が必要だと思います。

2022-08-21 15:36 UTC, mitosagi requested changes

2022-08-21 15:36 UTC, mitosagi commented on v3/packages.json
> +      "files": [{ "filename": "script/丸付折線テキスト.obj" }]
これまでのところ、検索性を考えてスクリプトをフォルダ分けするようにしています。
```suggestion
      "files": [{ "filename": "script/kame/丸付折線テキスト.obj" }]
```

2022-08-21 15:36 UTC, mitosagi commented on v3/packages.json
> +      "files": [{ "filename": "script/coord.anm" }]
```suggestion
      "files": [{ "filename": "script/coord/coord.anm" }]
```

2022-08-21 15:56 UTC, glyzinieh commented
修正させていただきました。
よろしくお願いします。

2022-08-21 16:30 UTC, hal-shu-sato requested changes
恐らく`nazono/SortEffect`の`archivePath`は、以前のままで大丈夫です。
`archivePath`は、圧縮ファイルのrootからの相対パスより、ファイル名を除いた部分を指定します。

2022-08-21 17:09 UTC, glyzinieh commented
こちらの環境の問題で勘違いをしていました。
ご指摘ありがとうございます。

2022-08-22 04:44 UTC, hal-shu-sato approved these changes
正常に動作します。
自動更新システム等、utilityがv3移行中のため、#311 のマージ後にマージします。
`list.json`のconflictは、マージ時に対応しておきます。

2022-08-22 15:36 UTC, hal-shu-sato approved these changes

2022-08-22 15:37 UTC, merged