Add specification documents
team-apm/apm-data pull request #326
Opened 2022-08-21 15:12 UTC by hal-shu-sato

## Description

- Add specification documents for 3 versions.

## Related Issue

## How Has This Been Tested?

## Checklist:

- [ ] ~~Updated the modification date in `mod.xml`.~~

2022-08-21 15:58 UTC, mitosagi requested changes
I would like to confirm one thing.

2022-08-21 15:58 UTC, mitosagi commented on v3/SPECIFICATION.md
> +## [packages_list.xml](./data/packages_list.xml)
```suggestion
## [packages.json](./packages.json)
```
Similarly, please change the other links in v3/SPECIFICATION.md.

2022-08-21 16:18 UTC, hal-shu-sato commented
I fixed it.

In my search, to enable symlinks in Git, we have to set `core.symlinks` to `true`.

2022-08-21 16:25 UTC, hal-shu-sato commented
Symbolic links were added to maintain the availability of v1.
However, since we are no longer supporting it, we may not have to take that step.
Also, jsDelivr does not seem to be supported.

2022-08-22 04:05 UTC, mitosagi commented
What about deleting v1 files?

2022-08-22 04:08 UTC, hal-shu-sato commented
I have a desire to keep the data files as legacy.
I am now thinking that I may remove Symlink.

2022-08-22 04:11 UTC, hal-shu-sato commented
By the way, I notice that I made a mistake regarding the necessary element in `SPECIFICATION.md`.
I will fix it.

2022-08-22 14:33 UTC, mitosagi approved these changes
Hopefully the documentation will help new participants.

Symbolic links can be removed at your own discretion.

2022-08-22 14:41 UTC, hal-shu-sato commented
I removed the symlink and rebased.

2022-08-22 15:33 UTC, merged