feat: add submitted packages
team-apm/apm-data pull request #474
Opened 2023-01-22 13:06 UTC by mitosagi

## Description

Add user-submitted packages. Thanks to everyone who contributed package data.

Adding the `isHidden` attribute to `sort.js`.

## Related Issue

- closes #425 
- closes #435 
- closes #436 
- closes #441 
- closes #444 
- closes #445 
- closes #471 

## How Has This Been Tested?

- Package can be installed
- Package works on AviUtl

## Checklist:

- [ ] ~~Updated the modification date in `mod.xml`.~~ To avoid conflicts

2023-02-23 06:42 UTC, hal-shu-sato requested changes
Sorry for the late review.
I have some points to request changes.

2023-02-23 06:42 UTC, hal-shu-sato commented on v3/packages.json
> +              }
The `*.ini` file is a configuration file, so we should not include it in `integrity`.

2023-02-23 06:42 UTC, hal-shu-sato commented on v3/packages.json
> +              }
Same as L2392-2395

2023-02-23 06:42 UTC, hal-shu-sato commented on v3/packages.json
> +      "files": [{ "filename": "plugins/auls_confirmclose.auf" }],
```suggestion
      "files": [{ "filename": "auls_confirmclose.auf" }],
```
The original version should be placed in the same directory as `aviutl.exe`, so we should do the same.

2023-02-23 06:42 UTC, hal-shu-sato commented on v3/packages.json
> +      "latestVersion": "1.4.0",
Sorry for the late review.
The new version is released and the `LevelMeter` directory has been added so could you add it?

2023-03-05 02:46 UTC, mitosagi commented
Corrected.

2023-04-04 13:51 UTC, mitosagi commented
お時間があるときに確認していただけるとうれしいです。

2023-04-04 13:52 UTC, mitosagi commented
お時間があるときに確認していただけるとうれしいです。

2023-04-07 06:55 UTC, hal-shu-sato approved these changes
It works fine.
Sorry for the late review.

2023-04-07 06:55 UTC, merged