Add hebiiro/ultimate plugin
team-apm/apm-data pull request #829
Opened 2024-09-22 09:21 UTC by glyzinieh

## Changes

- `hebiiro/UltimatePlugin`を追加
- `hebiiro/python32`を追加

## Related Issue

- https://github.com/team-apm/apm-data/issues/694
- https://github.com/team-apm/apm-data/issues/703
- https://github.com/team-apm/apm-data/issues/735

2024-09-22 11:36 UTC, glyzinieh commented
@mitosagi schemaが更新されていないようです。

- https://github.com/team-apm/apm-schema/pull/149/

2024-10-07 03:24 UTC, mitosagi commented
@hal-shu-sato Conflicts実装PRのレビューをお願いします🙏

2024-11-01 04:31 UTC, hal-shu-sato commented
遅くなりました。
マージしました。

2024-11-02 00:12 UTC, mitosagi commented
- https://github.com/team-apm/apm/pull/1882 これもセットです！

2025-01-26 13:02 UTC, mitosagi requested changes
長らくお待たせしてますが、この３か所を修正後マージできると思います。
今回のapmリリースで https://github.com/team-apm/apm-data/issues/694#issuecomment-1878312650 の心配はすべて解決されています

2025-01-27 22:21 UTC, mitosagi requested changes
ここを忘れていました…

2025-01-27 22:21 UTC, mitosagi commented on v3/packages.json
> +          "filename": "ultimate.auf",
```suggestion
          "filename": "plugins/ultimate.auf",
```

2025-01-27 22:21 UTC, mitosagi commented on v3/packages.json
> +          "filename": "ultimate.auf",
readme通りの配置にしておく

2025-01-27 22:21 UTC, mitosagi commented on v3/packages.json
> +          "filename": "ultimate.aul",
```suggestion
          "filename": "plugins/ultimate.aul",
```

2025-01-29 14:46 UTC, mitosagi approved these changes
よさそうです

2025-01-29 14:47 UTC, glyzinieh commented
ありがとうございます

2025-02-01 09:32 UTC, merged